### ISSUE TITLE
Question - is it possible to incorporate a single variable to a list defined in YAML.

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#150]
Good day,

For my backup server I want to define the password in locals to leverage a data object.

````hcl
module "aci" {
  source  = "netascode/nac-aci/aci"
  version = "0.9.1"
  model   = local.model
  yaml_directories = [
    "data/*",
    "data/**/*",
  ]
  manage_access_policies    = true
  manage_fabric_policies    = true
  manage_pod_policies       = true
  manage_node_policies      = true
  manage_interface_policies = true
  manage_tenants            = true
}

locals {
  model = {
    apic = {
      fabric_policies = {
        remote_locations = [{
          name = "backup_server"
          password = data.key_vault.password
        }]
      }
    }
  }
}
````

and my yaml file looks like this:

````yaml
---
apic:
  fabric_policies:
    remote_locations:
      - name: backup_server
        hostname_ip: 192.168.1.20
        protocol: sftp
        path: /
        auth_type: password
        username: backup_user
        mgmt_epg: oob
````

This will try to create 2x objects that is named backup_server, is it possible to instead merge them?

br
Jørgen

**Comment by therealdoug** [comment]
I think this has to do with the [utils_yaml_merge](https://github.com/netascode/terraform-provider-utils) provider, since it matches on all primitive types.

The following seems to work, but not a great solution for what I think you're trying to accomplish

```hcl
locals {
  model = {
    apic = {
      fabric_policies = {
        remote_locations = [{
          name = "backup_server"
          hostname_ip = "192.168.1.20"
          protocol = "sftp"
          path = "/"
          auth_type = "password"
          username = "backup_user"
          mgmt_epg = "oob"
          password = "MuHP4ssw0rd"
        }]
      }
    }
  }
}
```

```yaml
---
apic:
  fabric_policies:
    remote_locations:
      - name: "backup_server"
        hostname_ip: "192.168.1.20"
        protocol: "sftp"
        path: /
        auth_type: password
        username: backup_user
        mgmt_epg: oob
```

You could also use an environment variable
- [https://github.com/netascode/terraform-aci-nac-aci/issues/80](https://github.com/netascode/terraform-aci-nac-aci/issues/80)
- [Official Docs for utils_yaml_merge](https://registry.terraform.io/providers/netascode/utils/latest/docs/data-sources/yaml_merge)

So an example would be to export the password to an environment var `muh_password`

```yaml
---
apic:
  fabric_policies:
    remote_locations:
      - name: "backup_server"
        hostname_ip: "192.168.1.20"
        protocol: "sftp"
        path: /
        auth_type: password
        username: backup_user
        mgmt_epg: oob
        password: !env muh_password
```
