### ISSUE TITLE
Geolocations - rack units

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#170]
Even though Cisco ACI does not have a description field per node in geolocations, it would be nice to have a filed in the code atleast where you can specify rack unit:

An example like this:
```yaml
apic:
  fabric_policies:
    geolocation:
      sites:
        - name: site1
          buildings:
            - name: building1
              floors:
                - name: floor1
                  rooms:
                    - name: room1
                      rows:
                        - name: row1
                          racks:
                            - name: rack1
                              nodes:
                                - 101
                                   unit: 42
                                - 102
                                   unit: 43
```

As far as I can understand this is just metadata anyways, so having track of the rack unit in the code atleast would be quite nice.

**Comment by andbyrne** [comment]
It's not possible since `nodes` is a simple list, not a list of dictionaries. Metadata like this is best added as comments.

```yaml
apic:
  fabric_policies:
    geolocation:
      sites:
        - name: site1
          buildings:
            - name: building1
              floors:
                - name: floor1
                  rooms:
                    - name: room1
                      rows:
                        - name: row1
                          racks:
                            - name: rack1
                              nodes:
                                - 101 # unit: 42
                                - 102 # unit: 43
```
