### ISSUE TITLE
Secondary IP address (ip_shared) does not get created with Floating L3out #503

### ISSUE THREAD

**Issue by robvand** [netascode/terraform-aci-nac-aci#182]
When configuring a floating L3out the secondary (ip_shared) IP address does not get created.

Example inventory:
```yaml

      l3outs:
        - name: isovalent.vrf-01-bgp-AS-65152
          description: L3out floating SVI with one node profile and two interface profiles
          alias: external-vrf
          vrf: vrf-01
          domain: isovalent.vrf-01

          node_profiles:
            - name: border-leafs
              nodes:
                - node_id: 1101
                  router_id: 101.2.1.1
                  
                - node_id: 1102
                  router_id: 102.2.1.1
                  
              interface_profiles:
                - name: vpc_to_isovalent-node-01
                  interfaces:
                    - node_id: 1101
                      channel: vpc_to_isovalent-node-01
                      mode: regular
                      vlan: 16
                      floating_svi: true
                      paths:
                        - floating_ip: 10.237.101.3/27
                          physical_domain: isovalent-nodes
                      ip: 10.237.101.1/27
                      ip_shared: 10.237.101.4/27
                      mtu: 1500

                    - node_id: 1102
                      channel: vpc_to_isovalent-node-01
                      mode: regular
                      vlan: 16
                      floating_svi: true
                      paths:
                        - floating_ip: 10.237.101.3/27
                          physical_domain: isovalent-nodes
                      ip_shared: 10.237.101.4/27
                      mtu: 1500    
```

Class and DN information for Secondary IP under floating L3out:
```json
{"l3extIp":{"attributes":{
    "dn":"uni/tn-isovalent/out-isovalent.vrf-01-bgp-AS-65152/lnodep-border-leafs/lifp-vpc_to_isovalent-node-01/vlifp-[topology/pod-1/node-1101]-[vlan-16]/addr-[10.237.101.4/27]",
"addr":"10.237.101.4/27","rn":"addr-[10.237.101.4/27]","status":"created"},"children":[]}}
```
