### ISSUE TITLE
fabric - leaf_switch_profiles are not generated.

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#210]
./main.tf
```hcl
module "aci" {
  source  = "netascode/nac-aci/aci"
  version = "0.9.3"
  model   = local.model
  yaml_directories = [
    "data/*",
    "data/**/*",
  ]
  manage_access_policies    = true
  manage_fabric_policies    = true
  manage_pod_policies       = true
  manage_node_policies      = true
  manage_interface_policies = true
  manage_tenants            = true
}
```

./data/fabric-policies/leaf_switch_profile.yaml
```yaml
---
apic:
  fabric_policies:
    leaf_switch_profiles:
      - name: LEAF1001
        selectors:
          - name: SEL1
            policy: ALL_LEAFS
            node_blocks:
              - name: BLOCK1
                from: 1001
        interface_profiles:
          - LEAF1001
```

Even though I've tried diffent file-names and different configurations, nothing is applied when i define leaf_switch_profiles.
```bash
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by jorgenspange** [comment]
The case seems to be the same for spine_switch_profiles.

Here is also my apic: values attached, if that's relevant.

```yaml
---
apic:
  version: '6.0.8f'
  auto_generate_switch_pod_profiles: true
  auto_generate_pod_profiles: true
  auto_generate_fabric_leaf_switch_interface_profiles: true
  auto_generate_fabric_spine_switch_interface_profiles: true
  auto_generate_access_leaf_switch_interface_profiles: true
  auto_generate_access_spine_switch_interface_profiles: true
  new_interface_configuration: true
  fabric_policies:
    leaf_switch_profile_name: "leaf-\\g<id>"
    leaf_interface_profile_name: "leaf-\\g<id>"
    leaf_switch_selector_name: "leaf-\\g<id>"
    spine_switch_profile_name: "spine-\\g<id>"
    spine_interface_profile_name: "spine-\\g<id>"
    spine_switch_selector_name: "spine-\\g<id>"
    pod_profile_name: "pod-\\g<id>"
    pod_profile_pod_selector_name: "pod-\\g<id>"
  access_policies:
    leaf_switch_profile_name: "leaf-\\g<id>"
    leaf_interface_profile_name: "leaf-\\g<id>"
    leaf_switch_selector_name: "leaf-\\g<id>"
    leaf_interface_selector_name: "eth-\\g<mod>-\\g<port>"
    leaf_interface_selector_sub_port_name: "eth-\\g<mod>-\\g<port>-\\g<sport>"
    fex_profile_name: "leaf-\\g<id>-fex-    \\g<fex>"
    fex_interface_selector_name: "eth-\\g<mod>-\\g<port>"
    spine_switch_profile_name: "spine-\\g<id>"
    spine_interface_profile_name: "spine-\\g<id>"
    spine_switch_selector_name: "spine-\\g<id>"
    spine_interface_selector_name: "eth-\\g<mod>-\\g<port>"
    vpc_group_name: "vpc-\\g<switch1_id>-\\g<switch2_id>"
```

**Comment by jorgenspange** [comment]
When I added the HCL code in main.tf

```hcl

```
I got prompted that the module was not installed:
```bash
╷
│ Error: Module not installed
│
│   on main.tf line 73:
│   73: module "aci_fabric_leaf_switch_profile" {
│
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
[jorgenspange@Jorgens-MBP ~/Documents/git/IaC-Prod-Base/proddcciscoaci (dc_flows) ]$ terraform init
Initializing the backend...
Initializing modules...
Downloading registry.terraform.io/netascode/nac-aci/aci 0.9.3 for aci_fabric_leaf_switch_profile...
- aci_fabric_leaf_switch_profile in .terraform/modules/aci_fabric_leaf_switch_profile/modules/terraform-aci-fabric-leaf-switch-profile
Initializing provider plugins...
- Reusing previous version of netascode/utils from the dependency lock file
- Reusing previous version of efficientip-labs/solidserver from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of ciscodevnet/aci from the dependency lock file
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of ciscodevnet/mso from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Using previously-installed netascode/utils v0.2.6
- Using previously-installed efficientip-labs/solidserver v1.1.23
- Using previously-installed hashicorp/null v3.2.3
- Using previously-installed ciscodevnet/aci v2.15.0
- Using previously-installed hashicorp/azurerm v4.11.0
- Using previously-installed hashicorp/random v3.6.3
- Using previously-installed ciscodevnet/mso v0.11.1
- Using previously-installed hashicorp/local v2.5.2
```

But after installation it doesnt work when the configuration is in yaml-format.
HCL seems to be working stable.

**Comment by andbyrne** [comment]
> The case seems to be the same for spine_switch_profiles.
> 
> Here is also my apic: values attached, if that's relevant.

As you have enabled `new_interface_configuration`, all of the other auto options (except `auto_generate_pod_profiles`) will not do anything.

The switch and interface profiles will instead be system generated based on the following:
1. The interface configuration under `apic.interface_policies.nodes`
2. The value of `fabric_policy_group` and `access_policy_group` under `apic.node_policies.nodes`

**Comment by jorgenspange** [comment]
@andbyrne Thanks for great input! Still I am having a hard time how to configure what I want then.
I want to assign node_control_policy to all my nodes. Could you show me a quick example on how to do that in yaml?

**Comment by jorgenspange** [comment]
Got it figured now!

```
---
apic:
   node_policies:
   nodes:
       - id: 101
         role: leaf
         fabric_policy_groups: leafs
       - id: 201
         role: spine
         fabric_policy_groups: spines
```

```yaml
---
apic:
  fabric_policies:
    switch_policies:
      node_control_policies:
        - name: DOM_TELEMETRY
          dom: true
          telemetry: telemetry
````

```yaml
---
apic:
  fabric_policies:
    leaf_switch_policy_groups:
      - name: leafs
        node_control_policy: DOM_TELEMETRY
    spine_switch_policy_groups:
      - name: spines
        node_control_policy: DOM_TELEMETRY
```

Does not seem like the documentation is updated with the fabric_policy_groups and access_policy_groups under nodes though:
https://developer.cisco.com/docs/nexus-as-code/node-registration/#classes

**Comment by andbyrne** [comment]
The documentation is aligned to function, so under Node Registration you should only see the attributes and examples relevant to that function.

Refer to these links for attributes and examples for [Fabric Spine Switch Profile](https://developer.cisco.com/docs/nexus-as-code/fabric-spine-switch-profile/) and [Fabric Leaf Switch Profile](https://developer.cisco.com/docs/nexus-as-code/fabric-leaf-switch-profile/).

I've recently updated the documentation to make it even clearer (including some of the missing code from the examples). This should appear at those links when the next version is released.

**Comment by jorgenspange** [comment]
Not sure if I understand, I'm talking about the attributes here:

```yaml
---
apic:
   node_policies:
   nodes:
       - id: 101
         role: leaf
         fabric_policy_groups: leafs
       - id: 201
         role: spine
         fabric_policy_groups: spines
```

And also as you mentioned fabric leaf switch profile is no longer available when using new_interface_config.
