### ISSUE TITLE
YAML Deep merge duplicates when ingesting locals.

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#214]
Good day,

Trying to merge yaml config and locals fails due to duplicate object:

```yaml
---
apic:
  tenants:
    - name: common
      l3outs:
          .......
              interface_profiles:
                - name: if_prfile
                  interfaces:
                    - node_id: 1337
                      ip: '10.13.37.250/24'
                      vlan: 1337
                      svi: true
                      floating_svi: true
                      paths:
                        - floating_ip: 10.13.37.251/24
                          physical_domain: access
                      bgp_peers:
                        - ip: '10.13.37.11'
                          remote_as: 65001
                          send_community: true
                          local_as: 65000
                        - ip: 10.13.37.12
                          remote_as: 65001
                          send_community: true
                          local_as: 65000
```

With the following defined in locals
./main.tf

```hcl
locals {
  model = {
    apic = {
      tenants = [{
        name  = "common"
        l3outs = [{
          name          = "l3out"
          node_profiles = [{
            name              = "node_prof"
            interface_profiles = [{
              name       = "if_prfile"
              interfaces = [{
                node_id  = 1337
                bgp_peers = [{
                  ip       = "10.13.37.12"
                  password = "blabla"
                }]
              }]
            }]
          }]
        }]
      }]
    }
  }
}
````

It fails like this:

```bash
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/aci/aci_tenants.tf line 1187, in locals:
│ 1187:                 remote_as                        = peer.remote_as
│
│ This object does not have an attribute named "remote_as".
╵
```

If I add 

```hcl
                  remote_as = 65001
````

It fails like this:

```bash
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Duplicate object key
│
│   on .terraform/modules/aci/modules/terraform-aci-l3out-interface-profile/main.tf line 474, in resource "aci_rest_managed" "bgpPeerP_floating":
│  474:   for_each   = { for item in local.floating_bgp_peers : item.key => item.value }
│     ├────────────────
│     │ item.key is "1337/1337/10.13.37.12"
│
│ Two different items produced the key "1337/1337/10.13.37.12" in this 'for' expression. If duplicates are expected, use the ellipsis (...) after the value expression to enable grouping by key.
╵
```

To me, this indicates that it is trying to loop through both the entry in the yaml file and defined in the locals.
While talking to Daniel on Cisco Live earlier this year he stated that this should be taken care of by yaml deep merge as long as the name corresponds.

Is it something I am doing wrong here?

**Comment by juchowan** [comment]
I think in this case you need to match all primitive values of that bgp neighbor so following config would work:

```yaml
locals {
  model = {
    apic = {
      tenants = [{
        name  = "ABC"
        l3outs = [{
          name          = "l3out"
          node_profiles = [{
            name              = "node_prof"
            interface_profiles = [{
              name       = "if_prfile"
              interfaces = [{
                node_id  = 1337
                bgp_peers = [{
                  ip       = "10.13.37.12"
                  password = "blabla"
                  remote_as = 65001
                  send_community = true
                  local_as = 65000
                }]
              }]
            }]
          }]
        }]
      }]
    }
  }
}
```

Note also that you are trying to update password and we ignore password changes due to the way that ACI works, so not sure you will achieve what you need with this config, as it will show no changes planned

**Comment by andbyrne** [comment]
It may be simpler to inject the password via environment variables. For example:

```
---
apic:
  tenants:
    - name: common
      l3outs:
          .......
              interface_profiles:
                - name: if_prfile
                  interfaces:
                    - node_id: 1337
                      ip: '10.13.37.250/24'
                      vlan: 1337
                      svi: true
                      floating_svi: true
                      paths:
                        - floating_ip: 10.13.37.251/24
                          physical_domain: access
                      bgp_peers:
                        - ip: '10.13.37.11'
                          remote_as: 65001
                          send_community: true
                          local_as: 65000
                          password: !env PASSWORD-10-13-37-11
                        - ip: 10.13.37.12
                          remote_as: 65001
                          send_community: true
                          local_as: 65000
                          password: !env PASSWORD-10-13-37-12
```
