### ISSUE TITLE
new interface configuration does not generate configuration

### ISSUE THREAD

**Issue by micronemo** [netascode/terraform-aci-nac-aci#221]
new interface configuration does not generate configuration with terraform plan

```
apic:
  new_interface_configuration: true
  interface_policies:
    nodes:
      - id: 101
        interfaces:
          - port: 30
            description: interface descr 1
            policy_group: SERVER1
      - id: 102
        interfaces:
          - port: 30
            description: interface descr 1
            policy_group: SERVER1
```
```
defaults:
  apic:
    version: "6.0.2h"
    auto_generate_switch_pod_profiles: true
    auto_generate_pod_profiles: true
    auto_generate_fabric_leaf_switch_interface_profiles: true
    auto_generate_fabric_spine_switch_interface_profiles: true
    auto_generate_access_leaf_switch_interface_profiles: true
    auto_generate_access_spine_switch_interface_profiles: true
    new_interface_configuration: true
    fabric_policies:
      leaf_switch_profile_name: "leaf-\\g<id>"
      leaf_interface_profile_name: "leaf-\\g<id>"
      leaf_switch_selector_name: "leaf-\\g<id>"
      leaf_interface_selector_name: "eth-\\g<mod>-\\g<port>"
      spine_switch_profile_name: "spine-\\g<id>"
      spine_interface_profile_name: "spine-\\g<id>"
      spine_switch_selector_name: "spine-\\g<id>"
      spine_interface_selector_name: "eth-\\g<mod>-\\g<port>"
      pod_profile_name: "pod-\\g<id>"
      pod_profile_pod_selector_name: "pod-\\g<id>"
    access_policies:
      leaf_switch_profile_name: "leaf-\\g<id>"
      leaf_interface_profile_name: "leaf-\\g<id>"
      leaf_switch_selector_name: "leaf-\\g<id>"
      leaf_interface_selector_name: "eth-\\g<mod>-\\g<port>"
      leaf_interface_selector_sub_port_name: "eth-\\g<mod>-\\g<port>-\\g<sport>"
      fex_profile_name: "leaf-\\g<id>-fex-\\g<fex>"
      fex_interface_selector_name: "eth-\\g<mod>-\\g<port>"
      spine_switch_profile_name: "spine-\\g<id>"
      spine_interface_profile_name: "spine-\\g<id>"
      spine_switch_selector_name: "spine-\\g<id>"
      spine_interface_selector_name: "eth-\\g<mod>-\\g<port>"
      vpc_group_name: "vpc-\\g<switch1_id>-\\g<switch2_id>"
```
```
module "aci" {
  source = "netascode/nac-aci/aci"

  yaml_directories = ["Data/Output", "Data/Default"]

  manage_access_policies    = true
  manage_fabric_policies    = true
  manage_pod_policies       = true
  manage_node_policies      = true
  manage_interface_policies = true
  manage_tenants            = true
}
```
