### ISSUE TITLE
Policy location

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#57]
I dont quite understand why the location of the policies is different, for example:

err_disabled_recovery resides under fabric_policies:
```yaml
apic:
  fabric_policies:
    err_disabled_recovery:
      interval: 360
      mcp_loop: true
      ep_move: true
      bpdu_guard: true
   ```
   
   and mcp resides under access_policies:
   ```yaml
apic:
  access_policies:
    mcp:
      action: false
      admin_state: true
      key: cisco
      frequency_sec: 5
      initial_delay: 300
      loop_detection: 5
      per_vlan: false
```
   even though both have the same path in the gui:
  
  ```
  Location in GUI: Fabric » Access Policies » Policies » Global » Error Disabled Recovery Policy
```
   ```
  Location in GUI: Fabric » Access Policies » Policies » Global » MCP Instance Policy default
  ```
