### ISSUE TITLE
Maintenance groups

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#60]
Maintenance groups does not seem to work, when applying them they show up as failed because no version is specified. 

Also using them fails:
![image](https://github.com/netascode/terraform-aci-nac-aci/assets/75736500/70257fed-2a20-4c38-8821-d4150e362c0b)
![image](https://github.com/netascode/terraform-aci-nac-aci/assets/75736500/f7ea1111-84e7-4677-8a92-f672847c1689)

Here is my config:

```yaml
---
apic:
  node_policies:
    update_groups:
      - name: odd
      - name: even
```

```yaml
---
apic:
  node_policies:
    nodes:
      - id: 2101
        pod: 1
        role: leaf
        update_group: odd
      - id: 2102
        pod: 1
        role: leaf
        name: LabDrLeaf2102
        update_group: even
      - id: 2901
        pod: 1
        role: spine
        update_group: odd
```
