### ISSUE TITLE
Feature Request: Add VPC Interface Support as Static Ports in Endpoint Group Module

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#65]
Would like to be able to add vpc interfaces as static ports in the Endpoint Group module.

**Comment by juchowan** [comment]
VPC interfaces can be added by specifying channel which maps to an IPG name of VPC interafce, example:
```
static_ports:
  - channel: KACI-UCSC220M4S-1
    vlan: 123
```
Is this what you're looking for?

**Comment by jorgenspange** [comment]
Got it!

Configured it like this in the epg:

```yaml
            static_ports:
              - channel: vpc027
                node_id: 2101
                node2_id: 2102
                vlan: 1203
              - channel: vpc028
                node_id: 2101
                node2_id: 2102
                vlan: 1203
```
