### ISSUE TITLE
Question: Sensitive content protection in the different yaml files

### ISSUE THREAD

**Issue by alexanderdeca** [netascode/terraform-aci-nac-aci#80]
Question: How to protect sensitive content ex. passwords in different yaml files?

**Comment by danischm** [comment]
You can make use of `!env` YAML tags to inject those at runtime. See: https://registry.terraform.io/providers/netascode/utils/latest/docs/data-sources/yaml_merge

**Comment by alexanderdeca** [comment]
Hey Daniel,

Thanks for the info, do you have an example for me using for example as it is not clear what to do based on the link you provided.

    aaa:
      login_domains:
      - name: tacacs-auth
        realm: tacacs
        description: TACACS+ Authentication
      - name: local
        realm: local
        description: Local Authentication
      tacacs_providers:
      - hostname_ip: 10.253.241.4
        description: TACACS+
        port: 49
        key: 'Staging2023'
        timeout: 5
        retries: 1
        mgmt_epg: oob
      remote_user_login_policy: no-login
      default_fallback_check: true
      default_login_domain: lodhacs
      default_realm: tacacs
      console_realm: local
      console_login_domain: local

where I would replace the KEY value.

Best regards

Alexander

From: Daniel Schmidt ***@***.***>
Date: Friday, 3 May 2024 at 09:19
To: netascode/terraform-aci-nac-aci ***@***.***>
Cc: Alexander Deca ***@***.***>, Author ***@***.***>
Subject: Re: [netascode/terraform-aci-nac-aci] Question: Sensitive content protection in the different yaml files (Issue #80)

You can make use of !env YAML tags to inject those at runtime. See: https://registry.terraform.io/providers/netascode/utils/latest/docs/data-sources/yaml_merge

**Comment by danischm** [comment]
You would have something like this:

```yaml
    aaa:
      tacacs_providers:
      - hostname_ip: 10.253.241.4
        description: TACACS+
        port: 49
        key: !env TACACS_KEY
        timeout: 5
        retries: 1
        mgmt_epg: oob
```

And then an environment variable defined like this:

```
$export TACACS_KEY=Staging2023
```
